# Generated by Django 3.1.6 on 2021-02-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('diagonal', models.CharField(max_length=250, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=250, verbose_name='тип дисплея')),
                ('resolution', models.CharField(max_length=250, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=250, verbose_name='объем батареи')),
                ('ran', models.CharField(max_length=250, verbose_name='оперативная память')),
                ('sd', models.BooleanField(default=True)),
                ('sd_valume_max', models.CharField(max_length=250, verbose_name='максимальный объем встроенной памяти')),
                ('main_cam_ap', models.CharField(max_length=250, verbose_name='Главная камера')),
                ('front_cam_ap', models.CharField(max_length=250, verbose_name='фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('diagonal', models.CharField(max_length=250, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=250, verbose_name='тип дисплея')),
                ('processor_freq', models.CharField(max_length=250, verbose_name='частота процессор')),
                ('ran', models.CharField(max_length=250, verbose_name='оперативная память')),
                ('video', models.CharField(max_length=250, verbose_name='видеокартка')),
                ('time_without_charge', models.CharField(max_length=250, verbose_name='время работы аккумулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
