# Generated by Django 3.1.6 on 2021-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210213_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_valume_max',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='максимальный объем встроенной памяти'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='наличие SD карты '),
        ),
    ]
